import type { Metadata } from 'next';
import Link from 'next/link';
import { toolsCatalog } from '@/lib/tools-catalog';
import { get as getSettings } from '@/server/tools/settings.cjs';
import { enabled } from '@/server/tools/config.cjs';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Vireon Tools — Công cụ nhỏ. Việc xong nhanh.', alternates: { canonical: '/tools' } };
export default async function ToolsPage() {
  const settings = (await getSettings()).values;
  const label = settings.billingEnabled ? `${settings.priceVnd.toLocaleString('vi-VN')} đ / lượt` : 'Beta miễn phí';
  const available = enabled();
  return <><section className="vt-hero"><span className="vt-eyebrow">BỘ CÔNG CỤ CHO CÔNG VIỆC HẰNG NGÀY</span><h1>Công cụ nhỏ.<br /><em>Việc xong nhanh.</em></h1><p>Bớt thao tác lặp lại với bảng tính, chứng từ và báo cáo.<br />Chọn đúng công cụ, nhận lại kết quả bạn có thể kiểm tra.</p><span className="vt-pill">{available ? 'Excel Rescue · ' + label : 'Excel Rescue · Chuẩn bị mở beta'}</span></section><section className="vt-grid" aria-label="Danh sách công cụ">{toolsCatalog.map((tool, i) => <article className={`vt-card vt-${tool.color}`} key={tool.slug}><div className="vt-card-top"><span className="vt-icon" aria-hidden="true">{tool.icon}</span><span className={`vt-pill ${i !== 0 ? 'vt-muted' : ''}`}>{i === 0 && available ? label : 'Sắp ra mắt'}</span></div><h2>{tool.name}</h2><h3>{tool.subtitle}</h3><p>{tool.description}</p><ul>{tool.features.map(f => <li key={f}>{f}</li>)}</ul><Link className={i === 0 ? 'vt-button' : 'vt-link'} href={`/tools/${tool.slug}`}>{i === 0 && available ? 'Dùng Excel Rescue' : 'Khám phá công cụ'} <span aria-hidden="true">↗</span></Link></article>)}</section><section className="vt-flow"><h2>Từ file đầu vào đến kết quả rõ ràng</h2><ol><li><b>01</b> Tải file</li><li><b>02</b> Chọn thao tác</li><li><b>03</b> Xem kết quả mẫu</li><li><b>04</b> Tải Excel</li></ol><p>{settings.billingEnabled ? 'Thanh toán MoMo thủ công sau khi có kết quả. Liên hệ Zalo để admin đối soát và kích hoạt tải file.' : 'Lượt mới miễn phí, không yêu cầu tài khoản.'}</p></section><section id="du-lieu" className="vt-policy"><div><span className="vt-eyebrow">DỮ LIỆU CỦA BẠN</span><h2>Chỉ xử lý cho lượt làm việc của bạn.</h2></div><div><p>File được xử lý trên hosting Vireon và lưu riêng tư {settings.driveEnabled ? 'trong Google Drive của Vireon' : 'trên máy chủ Vireon'}, không gửi tới AI/OCR. QR hoặc liên kết khôi phục cho phép mở lại công việc; lượt có phí được tải sau khi admin kích hoạt.</p><p>Lượt mới lưu file tối đa 30 ngày từ lúc tạo, không gia hạn khi thanh toán hoặc quét QR. File hết quyền truy cập ngay khi hết hạn và được cron xóa vĩnh viễn ở lần dọn thành công tiếp theo. Có thể xóa sớm. Giữ riêng QR/liên kết; mất cả cookie lẫn liên kết sẽ không tự khôi phục được.</p><p>Kết quả gồm giá trị dữ liệu và báo cáo thay đổi; không bảo toàn định dạng, macro hay công thức gốc. Hãy kiểm tra kết quả trước khi sử dụng.</p></div></section></>;
}
