'use client';
import Image from 'next/image';
import { useCallback, useEffect, useState } from 'react';
type Cell = string | number | boolean | null | { date: string };
export type AccessJob = { id: string; expiresAt: string; status: string; storageReady: boolean; canDownload: boolean; files?: { name: string }[]; operation?: string | null; result?: { tables: { name: string; headers: string[]; rows: Cell[][]; totalRows: number }[] } | null; payment: { status: string; amount: number; requiresPayment: boolean; momo?: { phone: string; name: string; zaloPhone: string; instructions: string }; reference: string } };
export function RecoveryPanel({ job }: { job: { id: string; expiresAt: string } }) {
  const [saved, setSaved] = useState<{ qr: string; url: string } | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => {
    const r = await fetch(`/api/tools/jobs/${job.id}/recovery`, { method: 'POST' });
    const body = await r.json(); if (!r.ok) throw new Error(body.error); return body;
  }, [job.id]);
  useEffect(() => { let active = true; void load().then(s => { if (active) setSaved(s); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [load]);
  return <section className="vt-panel"><h2>QR giao dịch · mở lại trên thiết bị khác</h2><p>Giữ QR này để quay lại công việc. Khi admin kích hoạt, tải lại trang hoặc quét QR là tải được file.</p><p className="vt-help">Hạn file: {new Date(job.expiresAt).toLocaleString('vi-VN')}. QR và liên kết cho phép truy cập dữ liệu của lượt này; giữ riêng chúng.</p>{!saved && !error && <p role="status">Đang tạo QR giao dịch…</p>}{saved && <div className="vt-recovery"><Image unoptimized src={saved.qr} width={240} height={240} alt="QR giao dịch mở lại công việc" /><div><label className="vt-field">Liên kết mở lại<input readOnly value={saved.url} onFocus={e => e.target.select()} /></label><a className="vt-button" download={`vireon-${job.id}-qr.png`} href={saved.qr}>Lưu ảnh QR</a><button className="vt-link" onClick={() => void navigator.clipboard.writeText(saved.url).catch(() => setError('Hãy chọn và sao chép liên kết trong ô bên trên.'))}>Sao chép liên kết</button></div></div>}{error && <p role="alert" className="vt-error">{error} <button className="vt-link" onClick={() => { setError(''); void load().then(setSaved).catch(e => setError(e.message)); }}>Thử tạo QR lại</button></p>}</section>;
}
export function ResultPreview({ job }: { job: AccessJob }) {
  if (!job.result) return null;
  const cell = (v: Cell) => v === null ? '' : typeof v === 'object' ? v.date : String(v);
  return <section className="vt-panel"><h2>Xem trước kết quả</h2><p className="vt-help">Tối đa 3 sheet, mỗi sheet 10 dòng mẫu. File tải về chứa kết quả đầy đủ.</p>{job.result.tables.slice(0, 3).map((table, i) => <details open key={i}><summary>{table.name} · {table.totalRows.toLocaleString('vi-VN')} dòng</summary><div className="vt-table-wrap" tabIndex={0} aria-label={'Xem trước ' + table.name}><table><thead><tr>{table.headers.map((h, k) => <th key={k}>{h}</th>)}</tr></thead><tbody>{table.rows.slice(0, 10).map((r, k) => <tr key={k}>{r.map((v, c) => <td key={c}>{cell(v)}</td>)}</tr>)}</tbody></table></div></details>)}</section>;
}
export function PaymentPanel({ job, refresh }: { job: AccessJob; refresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const ref = job.payment.reference || 'VR' + job.id.replaceAll('-', '').toUpperCase();
  const message = `Chào Vireon, tôi muốn kích hoạt giao dịch ${ref}.\nFile: ${(job.files || []).map(f => f.name).join(', ')}\nSố tiền: ${job.payment.amount.toLocaleString('vi-VN')} đ.\nTôi sẽ gửi kèm thông tin/ảnh chuyển tiền để đối soát.`;
  async function copy() { try { await navigator.clipboard.writeText(message); setNotice('Đã sao chép. Mở Zalo và dán nội dung gửi cho admin.'); } catch { setError('Không sao chép được tự động. Hãy chọn nội dung trong ô thông tin giao dịch bên dưới.'); } }
  if (job.status !== 'ready' || !job.storageReady) return <section className="vt-panel" role="status"><h2>Đang hoàn tất file kết quả</h2><p>Chờ xử lý và lưu file thành công trước khi chuyển tiền. Bạn có thể lưu QR và quay lại sau.</p></section>;
  const activated = job.canDownload;
  return <section className="vt-panel"><span className="vt-pill">{activated ? 'Sẵn sàng tải file' : 'Chờ kích hoạt giao dịch'}</span><h2>{activated ? 'Kết quả của bạn đã được mở khóa' : 'Thanh toán & liên hệ Zalo'}</h2><label className="vt-field">Mã giao dịch<input readOnly value={ref} onFocus={e => e.target.select()} /></label><p className="vt-wrap">File: {(job.files || []).map(f => f.name).join(', ')}</p><p><b>{job.payment.amount ? job.payment.amount.toLocaleString('vi-VN') + ' đ' : 'Miễn phí'}</b> · Hạn tải {new Date(job.expiresAt).toLocaleString('vi-VN')}</p>
    {activated ? <><a className="vt-button" href={`/api/tools/jobs/${job.id}/download`}>Tải kết quả Excel ↓</a><p>Quét lại QR hoặc mở liên kết đã lưu để tải trên thiết bị khác trước khi hết hạn.</p></> : <><div className="vt-notice"><b>MoMo: {job.payment.momo?.phone} — {job.payment.momo?.name}</b><p>Nội dung chuyển tiền: <strong className="vt-wrap">{ref}</strong></p><p>{job.payment.momo?.instructions}</p></div><p>Liên hệ Zalo để được hướng dẫn hoặc chuyển tiền rồi nhắn admin kèm mã giao dịch này. Admin đối soát và kích hoạt đúng file.</p><div className="vt-actions"><button className="vt-button" onClick={() => void copy()}>Sao chép thông tin giao dịch</button>{job.payment.momo?.zaloPhone && <a className="vt-button" href={`https://zalo.me/${job.payment.momo.zaloPhone}`} target="_blank" rel="noreferrer">Liên hệ Zalo ↗</a>}</div><details><summary>Thông tin để gửi qua Zalo</summary><textarea className="vt-message" aria-label="Thông tin giao dịch để gửi Zalo" readOnly rows={4} value={message} onFocus={e => e.target.select()} /></details><p className="vt-help">QR ngay bên dưới dùng để mở lại giao dịch, không phải QR chuyển tiền. Không cần nhập mã tải; sau khi được kích hoạt chỉ cần tải lại trang.</p><button className="vt-link" disabled={busy} onClick={() => { setBusy(true); setError(''); void refresh().catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Tôi đã liên hệ · Kiểm tra kích hoạt</button></>}
    {notice && <p role="status">{notice}</p>}{error && <p role="alert" className="vt-error">{error}</p>}
  </section>;
}
