'use client';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useRef, useState } from 'react';
import { PaymentPanel, RecoveryPanel, type AccessJob } from './access-panel';
type Cell = string | number | boolean | null | { date: string };
type Sheet = { name: string; headers: { id: string; name: string }[]; rows: number; sample: { row: number; values: Cell[] }[] };
type FileMeta = { id: string; name: string; sheets: Sheet[] };
type Source = { fileId: string; sheet: string; keys: number[]; compare: number[]; names: string[] };
type Operation = 'deduplicate' | 'merge' | 'compare';
type Job = AccessJob & { id: string; status: string; phase: string; operation: Operation | null; expiresAt: string; files: { id: string; name: string; uploaded: number }[]; metadata: { files: FileMeta[]; warnings: string[] } | null; result: { stats: Record<string, number>; warnings: string[]; tables: { name: string; headers: string[]; rows: Cell[][]; totalRows: number }[] } | null; error: string | null; canDownload: boolean };
const operations = [{ id: 'deduplicate' as const, label: 'Loại dòng trùng', hint: '1 file · giữ dòng đầu hoặc cuối' }, { id: 'merge' as const, label: 'Ghép các file', hint: '2–5 file · ghép theo tên cột' }, { id: 'compare' as const, label: 'Đối chiếu A / B', hint: '2 file · tìm điểm khác nhau' }];
const statuses: Record<string, string> = { uploading: 'Đang tải file', queued: 'Đang chờ đến lượt', processing: 'Đang xử lý', configured: 'Sẵn sàng chọn cấu hình', ready: 'Đã có kết quả', failed: 'Chưa xử lý được', expired: 'Đã hết hạn' };
const statsLabels: Record<string, string> = { inputRows: 'Dòng đầu vào', outputRows: 'Dòng kết quả', removedRows: 'Dòng loại trùng', duplicateGroups: 'Nhóm trùng', blankKeys: 'Khóa trống giữ lại', files: 'File đã ghép', onlyA: 'Chỉ có ở A', onlyB: 'Chỉ có ở B', changedCells: 'Ô khác nhau', matched: 'Dòng khớp', unresolvedRows: 'Dòng cần kiểm tra khóa' };
function display(value: Cell) { return value === null ? '' : typeof value === 'object' ? value.date : String(value); }
async function api<T = Job>(path: string, method = 'GET', body?: unknown): Promise<T> {
  const response = await fetch('/api/tools/' + path, { method, credentials: 'same-origin', headers: body !== undefined ? { 'Content-Type': 'application/json' } : {}, body: body !== undefined ? JSON.stringify(body) : undefined, cache: 'no-store' });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Không kết nối được máy chủ.'); return data as T;
}
function Table({ headers, rows }: { headers: string[]; rows: Cell[][] }) { return <div className="vt-table-wrap" tabIndex={0} aria-label="Bảng dữ liệu, có thể cuộn ngang"><table><thead><tr>{headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j} title={display(c)}>{display(c)}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="vt-empty">Không có dòng trong nhóm này.</p>}</div>; }
export default function ExcelWizard({ limits }: { limits: { fileBytes: number; files: number; rows: number; cells: number } }) {
  const router = useRouter();
  const [operation, setOperation] = useState<Operation>('deduplicate'); const [files, setFiles] = useState<File[]>([]);
  const [job, setJob] = useState<Job | null>(null); const [sources, setSources] = useState<Source[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [progress, setProgress] = useState('');
  const [offer, setOffer] = useState({ freeBeta: true, priceVnd: 0, driveEnabled: false });
  const [ready, setReady] = useState(false); const [consent, setConsent] = useState(false); const [drag, setDrag] = useState(false);
  const [trim, setTrim] = useState(false); const [ignoreCase, setIgnoreCase] = useState(false); const [keep, setKeep] = useState('first');
  const [includeSource, setIncludeSource] = useState(true); const [includeMatched, setIncludeMatched] = useState(true);
  const [tolerance, setTolerance] = useState('0'); const [toleranceMode, setToleranceMode] = useState('absolute');
  const [history, setHistory] = useState<{ id: string; status: string; operation: Operation | null }[]>([]);
  const initialized = useRef(''); const requestKey = useRef<string | null>(null);
  const refreshHistory = useCallback(async () => { const data = await api<{ jobs: { id: string; status: string; operation: Operation | null }[] }>('jobs'); setHistory(data.jobs); }, []);
  const acceptJob = useCallback((data: Job) => {
    setJob(data);
    if (!data.metadata || initialized.current === data.id) return;
    initialized.current = data.id;
    setSources(data.metadata.files.map(f => { const s = f.sheets[0]; return { fileId: f.id, sheet: s.name, keys: [0], compare: [s.headers.length > 1 ? 1 : 0], names: s.headers.map(h => h.name) }; }));
    setOperation(current => data.operation || (data.files.length === 1 ? 'deduplicate' : data.files.length > 2 || current === 'deduplicate' ? 'merge' : current));
  }, []);
  const loadJob = useCallback(async (id: string) => { const data: Job = await api('jobs/' + id); acceptJob(data); window.history.replaceState(null, '', window.location.pathname + '?job=' + data.id); return data; }, [acceptJob]);
  useEffect(() => { let active = true; (async () => {
    const session = await api<{ freeBeta: boolean; priceVnd: number; driveEnabled: boolean }>('session', 'POST');
    if (!active) return; setOffer(session); setReady(true);
    const token = new URLSearchParams(window.location.hash.slice(1)).get('resume');
    if (token) { const restored: Job = await api('resume', 'POST', { token }); if (active) { acceptJob(restored); window.history.replaceState(null, '', window.location.pathname + '?job=' + restored.id); } }
    else { const id = new URLSearchParams(window.location.search).get('job'); if (id && active) await loadJob(id); }
    if (active) await refreshHistory();
  })().catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [refreshHistory, acceptJob, loadJob]);
  useEffect(() => {
    if (!job || !(['queued', 'processing'].includes(job.status) || job.status === 'ready' && !job.storageReady)) return;
    let active = true; let timer: ReturnType<typeof setTimeout>;
    async function poll() {
      try { const next: Job = await api('jobs/' + job!.id); if (active) { acceptJob(next); setError(''); if (['queued', 'processing'].includes(next.status) || next.status === 'ready' && !next.storageReady) timer = setTimeout(poll, 3000); else { void refreshHistory().catch(() => {}); if (next.status === 'ready' && next.payment.requiresPayment) router.push('/tools/checkout/' + next.id); } } }
      catch (e) { if (active) { setError(e instanceof Error ? e.message : 'Mất kết nối.'); timer = setTimeout(poll, 10000); } }
    }
    timer = setTimeout(poll, 3000); return () => { active = false; clearTimeout(timer); };
  }, [job, refreshHistory, acceptJob, router]);
  function changeSource(index: number, patch: Partial<Source>) { setSources(current => current.map((s, i) => i === index ? { ...s, ...patch } : s)); }
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'Có lỗi xảy ra.'); } finally { setBusy(false); setProgress(''); } }
  function pick(list: File[]) { setFiles(list); requestKey.current = null; setError(''); }
  async function upload() {
    if (!consent) throw new Error('Vui lòng đồng ý xử lý và lưu file trước khi tải.');
    const count = files.length;
    if (operation === 'deduplicate' ? count !== 1 : operation === 'compare' ? count !== 2 : count < 2 || count > limits.files) throw new Error('Số file chưa phù hợp với thao tác đã chọn.');
    if (files.some(f => !/\.(xlsx|csv)$/i.test(f.name) || f.size > limits.fileBytes || f.size === 0)) throw new Error('Chỉ nhận XLSX/CSV không rỗng, mỗi file tối đa ' + limits.fileBytes / 1048576 + ' MB.');
    requestKey.current ||= crypto.randomUUID();
    const created: Job = await api('jobs', 'POST', { requestKey: requestKey.current, expectedPrice: offer.priceVnd, files: files.map(f => ({ name: f.name, size: f.size })) }); setJob(created); window.history.replaceState(null, '', window.location.pathname + '?job=' + created.id);
    for (let i = 0; i < files.length; i++) {
      setProgress(`Đang tải file ${i + 1}/${files.length}…`);
      const response = await fetch(`/api/tools/jobs/${created.id}/file?file=${created.files[i].id}`, { method: 'PUT', body: files[i], headers: { 'Content-Type': 'application/octet-stream' }, credentials: 'same-origin' });
      if (!response.ok) throw new Error((await response.json()).error || 'Tải file chưa hoàn tất.');
    }
    setJob(await api(`jobs/${created.id}/inspect`, 'POST')); await refreshHistory();
  }
  async function process() { setJob(await api(`jobs/${job!.id}/process`, 'POST', { operation, sources, trim, ignoreCase, keep, includeSource, includeMatched, tolerance: Number(tolerance), toleranceMode })); }
  function reset() { window.history.replaceState(null, '', window.location.pathname); setJob(null); setFiles([]); setSources([]); initialized.current = ''; requestKey.current = null; setError(''); setConsent(false); }
  const configuring = job?.status === 'configured';
  const waiting = job && ['queued', 'processing'].includes(job.status);
  return <><ol className="vt-steps" aria-label="Các bước"><li className={!job || job.status === 'uploading' ? 'active' : ''}>01 · Tải dữ liệu</li><li className={configuring ? 'active' : ''}>02 · Chọn quy tắc</li><li className={waiting ? 'active' : ''}>03 · Xử lý</li><li className={job?.status === 'ready' ? 'active' : ''}>04 · Xem & tải</li></ol>
    {error && <div role="alert" className="vt-error">{error}</div>}
    {!job && <section className="vt-panel"><h2>Bạn muốn làm gì với bảng tính?</h2><div className="vt-options">{operations.map(op => <button type="button" key={op.id} aria-pressed={operation === op.id} className={operation === op.id ? 'selected' : ''} onClick={() => setOperation(op.id)}><b>{op.label}</b><small>{op.hint}</small></button>)}</div><label className={`vt-drop ${drag ? 'drag' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); pick(Array.from(e.dataTransfer.files)); }}><span aria-hidden="true">↑</span><b>Kéo file vào đây hoặc chọn từ máy</b><small>XLSX / CSV UTF-8 · tối đa {limits.fileBytes / 1048576} MB/file</small><input type="file" aria-label="Chọn file Excel hoặc CSV" accept=".xlsx,.csv" multiple={operation !== 'deduplicate'} onChange={e => pick(Array.from(e.target.files || []))} /></label>{files.length > 0 && <ol className="vt-files">{files.map((f, i) => <li key={i}><span>{i + 1}. {f.name}</span><small>{(f.size / 1024).toFixed(1)} KB</small></li>)}</ol>}<p className="vt-help">Tổng tối đa {limits.rows.toLocaleString('vi-VN')} dòng, {limits.cells.toLocaleString('vi-VN')} ô trong các file; 100 cột/sheet. Dòng đầu tiên là tiêu đề. Không nhận XLS, XLSM, ô gộp hay file có mật khẩu.</p><label className="vt-check"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} />Tôi có quyền sử dụng dữ liệu này và đồng ý xử lý trên máy chủ, lưu file riêng tư {offer.driveEnabled ? 'trên Google Drive của Vireon' : 'trên máy chủ Vireon'} tối đa 30 ngày theo <a href="/tools#du-lieu" target="_blank" rel="noreferrer">chính sách dữ liệu</a>.</label><p className="vt-help">{offer.freeBeta ? 'Lượt mới miễn phí.' : `Phí mỗi lượt: ${offer.priceVnd.toLocaleString('vi-VN')} đ; thanh toán sau khi có kết quả.`} Lưu QR để mở lại trên thiết bị khác. Xuất giá trị, không giữ định dạng/công thức gốc.</p><button className="vt-button" disabled={!ready || busy || !consent || !files.length} onClick={() => void run(upload)}>{busy ? progress || 'Đang chuẩn bị…' : 'Tải file & đọc cấu trúc →'}</button></section>}
    {job && <div className="vt-jobbar"><span><b>{statuses[job.status] || job.status}</b><small>Hết hạn: {new Date(job.expiresAt).toLocaleString('vi-VN')}</small></span><div><button className="vt-link" disabled={busy} onClick={reset}>Lượt mới</button><button className="vt-link" disabled={busy || job.status === 'processing'} onClick={() => void run(async () => { await api('jobs/' + job.id, 'DELETE'); reset(); await refreshHistory(); })}>Xóa lượt này</button></div></div>}
    {waiting && <section className="vt-panel vt-wait" role="status" aria-live="polite"><span className="vt-spinner" /><h2>{job.phase === 'inspect' ? 'Đang kiểm tra cấu trúc file' : 'Đang xử lý theo quy tắc bạn chọn'}</h2><p>Mỗi lượt được xử lý riêng. Có thể chờ vài phút khi hàng đợi đang bận.</p><p>Bạn có thể lưu QR bên dưới, rời trang và mở lại lượt này trên thiết bị khác.</p></section>}
    {job?.status === 'uploading' && !busy && <section className="vt-panel"><h2>File chưa được tải đầy đủ</h2><p>Nếu vừa mất kết nối, bạn có thể thử tải lại các file đang chọn.</p>{files.length > 0 && <button className="vt-button" onClick={() => void run(upload)}>Tiếp tục tải file</button>}</section>}
    {configuring && job.metadata && <section className="vt-panel"><h2>Chọn quy tắc xử lý</h2><label className="vt-field">Thao tác<select aria-label="Thao tác" value={operation} onChange={e => setOperation(e.target.value as Operation)}>{operations.filter(op => op.id === 'deduplicate' ? job.files.length === 1 : op.id === 'compare' ? job.files.length === 2 : job.files.length >= 2).map(op => <option key={op.id} value={op.id}>{op.label}</option>)}</select></label>{job.metadata.warnings.map((w, i) => <p className="vt-notice" key={i}>{w}</p>)}
      {sources.map((source, index) => { const file = job.metadata!.files.find(f => f.id === source.fileId)!; const sheet = file.sheets.find(s => s.name === source.sheet)!; return <fieldset className="vt-source" key={source.fileId}><legend>{operation === 'compare' ? index === 0 ? 'Bảng A' : 'Bảng B' : `File ${index + 1}`} · {file.name}</legend><label className="vt-field">Sheet<select value={source.sheet} onChange={e => { const next = file.sheets.find(s => s.name === e.target.value)!; changeSource(index, { sheet: next.name, keys: [0], compare: [next.headers.length > 1 ? 1 : 0], names: next.headers.map(h => h.name) }); }}>{file.sheets.map(s => <option key={s.name} value={s.name}>{s.name} · {s.rows} dòng</option>)}</select></label>
        {operation === 'merge' ? <><p className="vt-help">Các cột có tên giống nhau sẽ được ghép chung. Sửa tên để ánh xạ; tên trong một file phải khác nhau.</p><div className="vt-mappings">{sheet.headers.map((h, i) => <label className="vt-field" key={i}>Cột {i + 1}: {h.name}<input maxLength={100} value={source.names[i] || ''} onChange={e => changeSource(index, { names: source.names.map((n, j) => i === j ? e.target.value : n) })} /></label>)}</div></> : <><p className="vt-help">Chọn 1–3 cột khóa theo thứ tự. Khóa trống được giữ lại hoặc đưa vào nhóm cần kiểm tra.</p>{source.keys.map((col, slot) => <label className="vt-field" key={slot}>Khóa {slot + 1}<select value={col} onChange={e => changeSource(index, { keys: source.keys.map((n, j) => j === slot ? Number(e.target.value) : n) })}>{sheet.headers.map((h, i) => <option key={i} value={i}>{i + 1}. {h.name}</option>)}</select></label>)}<div className="vt-actions"><button className="vt-link" disabled={source.keys.length >= Math.min(3, sheet.headers.length)} onClick={() => changeSource(index, { keys: [...source.keys, sheet.headers.findIndex((_, i) => !source.keys.includes(i))] })}>+ Thêm cột khóa</button>{source.keys.length > 1 && <button className="vt-link" onClick={() => changeSource(index, { keys: source.keys.slice(0, -1) })}>Bớt cột khóa</button>}</div></>}
        {operation === 'compare' && <><p className="vt-help">Cặp cột so sánh số 1 ở A tương ứng số 1 ở B; các cặp tiếp theo cũng vậy.</p>{source.compare.map((col, slot) => <label className="vt-field" key={slot}>Cột so sánh {slot + 1}<select value={col} onChange={e => changeSource(index, { compare: source.compare.map((n, j) => j === slot ? Number(e.target.value) : n) })}>{sheet.headers.map((h, i) => <option key={i} value={i}>{i + 1}. {h.name}</option>)}</select></label>)}<div className="vt-actions"><button className="vt-link" disabled={source.compare.length >= sheet.headers.length} onClick={() => changeSource(index, { compare: [...source.compare, sheet.headers.findIndex((_, i) => !source.compare.includes(i))] })}>+ Thêm cột so sánh</button>{source.compare.length > 1 && <button className="vt-link" onClick={() => changeSource(index, { compare: source.compare.slice(0, -1) })}>Bớt cột so sánh</button>}</div></>}
        <details><summary>Xem 3 dòng đầu</summary><Table headers={sheet.headers.map(h => h.name)} rows={sheet.sample.map(r => r.values)} /></details></fieldset>; })}
      <div className="vt-settings">{operation !== 'merge' && <><label className="vt-check"><input type="checkbox" checked={trim} onChange={e => setTrim(e.target.checked)} />Bỏ khoảng trắng đầu/cuối khi so khớp</label><label className="vt-check"><input type="checkbox" checked={ignoreCase} onChange={e => setIgnoreCase(e.target.checked)} />Không phân biệt hoa/thường khi so khớp</label></>}{operation === 'deduplicate' && <label className="vt-field">Khi trùng khóa<select value={keep} onChange={e => setKeep(e.target.value)}><option value="first">Giữ dòng đầu tiên</option><option value="last">Giữ dòng cuối cùng</option></select></label>}{operation === 'merge' && <label className="vt-check"><input type="checkbox" checked={includeSource} onChange={e => setIncludeSource(e.target.checked)} />Thêm cột tên file và sheet nguồn</label>}{operation === 'compare' && <><div className="vt-mappings"><label className="vt-field">Dung sai số<input type="number" min="0" max="1000000000" step="any" value={tolerance} onChange={e => setTolerance(e.target.value)} /></label><label className="vt-field">Cách tính<select value={toleranceMode} onChange={e => setToleranceMode(e.target.value)}><option value="absolute">Chênh lệch tuyệt đối</option><option value="percent">% theo giá trị tuyệt đối của A</option></select></label></div><p className="vt-help">Mặc định 0: so sánh chính xác. Chỉ áp dụng với ô số XLSX; khi A = 0, dung sai % cũng bằng 0.</p><label className="vt-check"><input type="checkbox" checked={includeMatched} onChange={e => setIncludeMatched(e.target.checked)} />Xuất cả các dòng khớp</label></>}</div><div className="vt-notice">Không thay đổi file gốc. Kết quả xuất dạng giá trị; ngày được ghi theo ISO. Công thức chỉ dùng giá trị đã lưu, không tính lại.</div><button className="vt-button" disabled={busy} onClick={() => void run(process)}>{busy ? 'Đang gửi…' : 'Xử lý & xem kết quả →'}</button></section>}
    {job?.status === 'failed' && <section className="vt-panel"><h2>Chưa thể hoàn tất lượt này</h2><p role="alert">{job.error}</p><button className="vt-button" disabled={busy} onClick={() => void run(async () => { setJob(await api(`jobs/${job.id}/retry`, 'POST')); })}>Thử lại nếu bị gián đoạn</button><p className="vt-help">Nếu file không hợp lệ hoặc vượt giới hạn, hãy sửa file và tạo lượt mới.</p></section>}
    {job?.status === 'ready' && job.result && <section className="vt-panel"><div className="vt-result-heading"><div><span className="vt-pill">{job.payment.requiresPayment ? 'Hoàn tất · Có phí' : 'Hoàn tất · Miễn phí'}</span><h2>Kết quả đã sẵn sàng</h2></div>{job.canDownload && !job.payment.requiresPayment && <a className="vt-button" href={`/api/tools/jobs/${job.id}/download`}>Tải kết quả Excel ↓</a>}</div><div className="vt-stats">{Object.entries(job.result.stats).map(([key, value]) => <div key={key}><b>{value.toLocaleString('vi-VN')}</b><span>{statsLabels[key] || key}</span></div>)}</div>{job.result.warnings.map((w, i) => <p className="vt-notice" key={i}>{w}</p>)}<p className="vt-help">Mỗi bảng hiển thị tối đa 10 dòng. File Excel chứa kết quả đầy đủ và sheet Summary ghi quy tắc xử lý.</p>{job.result.tables.slice(0, 3).map(t => <details key={t.name} open><summary>{t.name} <span>· {t.totalRows.toLocaleString('vi-VN')} dòng</span></summary><Table headers={t.headers} rows={t.rows} /></details>)}</section>}
    {job?.status === 'ready' && job.payment.requiresPayment && <PaymentPanel key={'payment-' + job.id} job={job} refresh={async () => { await loadJob(job.id); }} />}
    {job && <RecoveryPanel key={'recovery-' + job.id} job={job} />}
    {history.length > 0 && <section className="vt-history"><h2>Các lượt trong trình duyệt này</h2>{history.map(h => <button key={h.id} disabled={busy} onClick={() => void run(async () => { initialized.current = ''; await loadJob(h.id); })}><span>{operations.find(op => op.id === h.operation)?.label || 'File đang chuẩn bị'}</span><small>{statuses[h.status] || h.status}</small><span aria-hidden="true">→</span></button>)}</section>}
  </>;
}
