SET NAMES utf8mb4;

CREATE TABLE BaoGiang (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  buoiHocId BIGINT UNSIGNED NOT NULL,
  giaoVienId BIGINT UNSIGNED NOT NULL,
  chuDe VARCHAR(255) NOT NULL,
  noiDung TEXT NULL,
  mucTieu TEXT NULL,
  baiTap TEXT NULL,
  nhanXetChung TEXT NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'nhap',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_BaoGiang_buoi_giaoVien (buoiHocId, giaoVienId),
  CONSTRAINT fk_BaoGiang_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_BaoGiang_BuoiHoc FOREIGN KEY (buoiHocId) REFERENCES BuoiHoc(id),
  CONSTRAINT fk_BaoGiang_GiaoVien FOREIGN KEY (giaoVienId) REFERENCES GiaoVien(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DanhGiaHocTap (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  lopHocId BIGINT UNSIGNED NOT NULL,
  buoiHocId BIGINT UNSIGNED NULL,
  loaiDanhGia VARCHAR(50) NOT NULL,
  tieuChi VARCHAR(150) NOT NULL,
  diemSo DECIMAL(6,2) NULL,
  mucDanhGia VARCHAR(50) NULL,
  nhanXet TEXT NULL,
  giaoVienId BIGINT UNSIGNED NOT NULL,
  ngayDanhGia DATE NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_DGHT_hocSinh_ngay (hocSinhId, ngayDanhGia),
  CONSTRAINT fk_DGHT_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_DGHT_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_DGHT_LopHoc FOREIGN KEY (lopHocId) REFERENCES LopHoc(id),
  CONSTRAINT fk_DGHT_BuoiHoc FOREIGN KEY (buoiHocId) REFERENCES BuoiHoc(id),
  CONSTRAINT fk_DGHT_GiaoVien FOREIGN KEY (giaoVienId) REFERENCES GiaoVien(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DanhMucKhoanThu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  maKhoanThu VARCHAR(30) NOT NULL,
  tenKhoanThu VARCHAR(255) NOT NULL,
  loaiKhoanThu VARCHAR(50) NOT NULL COMMENT 'hoc_phi, tien_an, dich_vu, tai_lieu, khac',
  soTienMacDinh DECIMAL(18,2) NULL,
  batBuoc TINYINT(1) NOT NULL DEFAULT 1,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  PRIMARY KEY (id),
  UNIQUE KEY uk_DMKThu_donVi_ma (donViId, maKhoanThu),
  CONSTRAINT fk_DMKThu_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE KyThu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  maKyThu VARCHAR(30) NOT NULL,
  tenKyThu VARCHAR(255) NOT NULL,
  loaiKy VARCHAR(30) NOT NULL COMMENT 'thang, khoa_hoc, hoc_ky, dot',
  tuNgay DATE NOT NULL,
  denNgay DATE NOT NULL,
  hanThanhToan DATE NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'nhap',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_KyThu_donVi_ma (donViId, maKyThu),
  CONSTRAINT fk_KyThu_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE KyThuKhoanThu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  kyThuId BIGINT UNSIGNED NOT NULL,
  danhMucKhoanThuId BIGINT UNSIGNED NOT NULL,
  soTien DECIMAL(18,2) NOT NULL,
  ghiChu VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_KyThu_KhoanThu (kyThuId, danhMucKhoanThuId),
  CONSTRAINT fk_KTKT_KyThu FOREIGN KEY (kyThuId) REFERENCES KyThu(id),
  CONSTRAINT fk_KTKT_DanhMuc FOREIGN KEY (danhMucKhoanThuId) REFERENCES DanhMucKhoanThu(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE KhoanPhaiThu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  kyThuId BIGINT UNSIGNED NOT NULL,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  tongTien DECIMAL(18,2) NOT NULL DEFAULT 0,
  giamTru DECIMAL(18,2) NOT NULL DEFAULT 0,
  daThu DECIMAL(18,2) NOT NULL DEFAULT 0,
  conLai DECIMAL(18,2) GENERATED ALWAYS AS (tongTien - giamTru - daThu) STORED,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'chua_thu',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_KPT_ky_hocSinh (kyThuId, hocSinhId),
  KEY ix_KPT_donVi_trangThai (donViId, trangThai),
  CONSTRAINT fk_KPT_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_KPT_KyThu FOREIGN KEY (kyThuId) REFERENCES KyThu(id),
  CONSTRAINT fk_KPT_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE KhoanPhaiThuChiTiet (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  khoanPhaiThuId BIGINT UNSIGNED NOT NULL,
  danhMucKhoanThuId BIGINT UNSIGNED NOT NULL,
  soTien DECIMAL(18,2) NOT NULL,
  giamTru DECIMAL(18,2) NOT NULL DEFAULT 0,
  ghiChu VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_KPTCT_kpt_danhMuc (khoanPhaiThuId, danhMucKhoanThuId),
  CONSTRAINT fk_KPTCT_KhoanPhaiThu FOREIGN KEY (khoanPhaiThuId) REFERENCES KhoanPhaiThu(id),
  CONSTRAINT fk_KPTCT_DanhMuc FOREIGN KEY (danhMucKhoanThuId) REFERENCES DanhMucKhoanThu(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PhieuThu (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  soPhieu VARCHAR(50) NOT NULL,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  phuHuynhId BIGINT UNSIGNED NULL,
  ngayThu DATETIME NOT NULL,
  tongTien DECIMAL(18,2) NOT NULL,
  phuongThuc VARCHAR(30) NOT NULL COMMENT 'tien_mat, chuyen_khoan, the, khac',
  nguoiThuId BIGINT UNSIGNED NOT NULL,
  noiDung VARCHAR(500) NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'da_thu',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_PhieuThu_donVi_soPhieu (donViId, soPhieu),
  CONSTRAINT fk_PhieuThu_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_PhieuThu_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_PhieuThu_PhuHuynh FOREIGN KEY (phuHuynhId) REFERENCES PhuHuynh(id),
  CONSTRAINT fk_PhieuThu_NguoiThu FOREIGN KEY (nguoiThuId) REFERENCES NguoiDung(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PhieuThuChiTiet (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  phieuThuId BIGINT UNSIGNED NOT NULL,
  khoanPhaiThuId BIGINT UNSIGNED NOT NULL,
  soTien DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_PTCT_PhieuThu FOREIGN KEY (phieuThuId) REFERENCES PhieuThu(id),
  CONSTRAINT fk_PTCT_KhoanPhaiThu FOREIGN KEY (khoanPhaiThuId) REFERENCES KhoanPhaiThu(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
