'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import './tools-admin.css';
type Settings = { billingEnabled: boolean; priceVnd: number; momoPhone: string; momoName: string; zaloPhone: string; instructions: string; driveEnabled: boolean; clientId: string; connected: boolean; hasClientSecret: boolean; driveEmail: string; folderId: string; callback: string };
type Job = { id: string; status: string; operation: string; expires_at: string; amount: number; payment_status: string; filenames: string; storage_provider: string };
type Issued = { reference: string; message: string; expiresAt: string; id: string };
async function api<T>(action: string, body?: unknown): Promise<T> {
  const r = await fetch('/api/admin/tools/' + action, { method: body === undefined ? 'GET' : 'POST', headers: body === undefined ? {} : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body), cache: 'no-store' });
  const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Không kết nối được máy chủ.'); return data;
}
const labels: Record<string, string> = { free: 'Miễn phí', unpaid: 'Chờ kích hoạt', reported: 'Chờ kích hoạt', approved: 'Đã kích hoạt' };
export default function ToolsAdmin() {
  const [settings, setSettings] = useState<Settings | null>(null), [secret, setSecret] = useState('');
  const [jobs, setJobs] = useState<Job[]>([]), [page, setPage] = useState(0), [issued, setIssued] = useState<Issued | null>(null);
  const [searchInput, setSearchInput] = useState(''), [search, setSearch] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const refresh = useCallback(async () => { setJobs((await api<{ jobs: Job[] }>('jobs?page=' + page + '&search=' + encodeURIComponent(search))).jobs); }, [page, search]);
  useEffect(() => {
    let active = true;
    void api<Settings>('settings').then(data => {
      if (!active) return;
      setSettings(data);
      const result = new URLSearchParams(location.search).get('drive');
      if (result) setNotice(result === 'connected' ? 'Đã kết nối Google. Kiểm tra Drive rồi bật lưu file.' : 'Kết nối Google chưa hoàn tất. Kiểm tra Client ID, secret, callback và đăng nhập lại đúng Gmail.');
    }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, []);
  useEffect(() => {
    let active = true;
    void api<{ jobs: Job[] }>('jobs?page=' + page + '&search=' + encodeURIComponent(search)).then(data => { if (active) setJobs(data.jobs); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [page, search]);
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Có lỗi xảy ra.'); } finally { setBusy(false); } }
  function edit<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings(s => s ? { ...s, [key]: value } : s); }
  async function approve(job: Job) {
    if (job.payment_status !== 'approved' && !window.confirm('Bạn đã đối soát giao dịch ' + 'VR' + job.id.replaceAll('-', '').toUpperCase() + ' với số tiền ' + job.amount.toLocaleString('vi-VN') + ' đ và muốn kích hoạt tải file?')) return;
    await run(async () => { setIssued(await api<Issued>('approve', { id: job.id, confirmed: true })); await refresh(); });
  }
  return <div className="admin-shell ta-shell"><div className="admin-topbar"><div><Link href="/admin">← Quản trị</Link><h1>Tools · Lưu trữ & thanh toán</h1><p>Google Drive cá nhân · MoMo đối soát thủ công · lưu file 30 ngày</p></div><button className="button-ghost" disabled={busy} onClick={() => void run(refresh)}>Làm mới danh sách</button></div>
    {error && <p className="ta-error" role="alert">{error}</p>}{notice && <p className="ta-notice" role="status">{notice}</p>}
    {issued && <section className="admin-card ta-issued"><h2>Đã kích hoạt giao dịch</h2><p>Chỉ gửi cho đúng khách hàng. Đây là nội dung để bạn sao chép, hệ thống chưa tự gửi tin nhắn.</p><textarea aria-label="Nội dung gửi khách hàng" readOnly rows={5} value={issued.message} /><div className="ta-actions"><button className="button-submit" onClick={() => void run(async () => { await navigator.clipboard.writeText(issued.message); setNotice('Đã sao chép nội dung gửi khách.'); })}>Sao chép gửi khách</button><button className="button-ghost" onClick={() => setIssued(null)}>Đóng thông báo</button></div></section>}
    <section className="admin-card"><h2>Tìm giao dịch & kích hoạt file</h2><p>Nhận mã giao dịch qua Zalo, đối soát tiền rồi kích hoạt. Khách tải lại trang hoặc quét QR để tải file.</p><form className="ta-actions" onSubmit={e => { e.preventDefault(); setPage(0); setSearch(searchInput.trim()); }}><label>Mã giao dịch<input placeholder="Dán mã VR… khách gửi qua Zalo" maxLength={64} value={searchInput} onChange={e => setSearchInput(e.target.value)} /></label><button className="button-submit" disabled={busy}>Tìm giao dịch</button><button type="button" className="button-ghost" onClick={() => { setSearchInput(''); setSearch(''); setPage(0); }}>Xem tất cả</button></form><div className="ta-table"><table className="admin-table"><thead><tr><th>Giao dịch / File</th><th>Thanh toán</th><th>Hạn tải</th><th>Xử lý</th></tr></thead><tbody>{jobs.map(j => <tr key={j.id}><td><code>{'VR' + j.id.replaceAll('-', '').toUpperCase()}</code><small>{j.filenames || 'Đang tải file'}</small><small>{j.operation || 'Đang chuẩn bị'} · {j.status} · {j.storage_provider}</small></td><td><b>{j.amount.toLocaleString('vi-VN')} đ</b><small>{labels[j.payment_status]}</small></td><td>{new Date(j.expires_at).toLocaleString('vi-VN')}</td><td>{j.amount > 0 && <button className="button-submit" disabled={busy || j.status !== 'ready'} onClick={() => void approve(j)}>{j.payment_status === 'approved' ? 'Sao chép thông báo' : 'Kích hoạt tải file'}</button>}</td></tr>)}</tbody></table></div>{!jobs.length && <p>Không có giao dịch phù hợp còn trong hạn lưu file.</p>}<div className="ta-actions"><button className="button-ghost" disabled={page === 0 || busy} onClick={() => setPage(p => p - 1)}>Trang trước</button><span>Trang {page + 1}</span><button className="button-ghost" disabled={jobs.length < 30 || busy} onClick={() => setPage(p => p + 1)}>Trang sau</button></div></section>
    {settings && <form onSubmit={e => { e.preventDefault(); void run(async () => { await api('settings', { ...settings, clientSecret: secret }); setSecret(''); setSettings(await api<Settings>('settings')); setNotice('Đã lưu. Giá và chế độ lưu trữ áp dụng cho lượt mới; lượt cũ giữ điều kiện đã tạo.'); }); }}><div className="ta-grid"><section className="admin-card"><h2>Thu phí qua MoMo</h2><label className="ta-check"><input type="checkbox" checked={settings.billingEnabled} onChange={e => edit('billingEnabled', e.target.checked)} />Bật thu phí cho lượt mới</label><label>Giá mỗi lượt xử lý (VND)<input type="number" min={0} max={10000000} step={1} value={settings.priceVnd} onChange={e => edit('priceVnd', Number(e.target.value))} /></label><label>Số điện thoại MoMo<input inputMode="tel" maxLength={20} value={settings.momoPhone} onChange={e => edit('momoPhone', e.target.value)} /></label><label>Số Zalo liên hệ<input inputMode="tel" maxLength={20} value={settings.zaloPhone} onChange={e => edit('zaloPhone', e.target.value)} /></label><label>Tên người nhận<input maxLength={100} value={settings.momoName} onChange={e => edit('momoName', e.target.value)} /></label><label>Hướng dẫn / liên hệ hỗ trợ<textarea maxLength={1000} rows={4} value={settings.instructions} onChange={e => edit('instructions', e.target.value)} /></label><p>Tắt thu phí: lượt mới tải miễn phí. Lượt đã tạo có giá riêng, không thay đổi khi bật/tắt công tắc. Không tích hợp xác nhận MoMo tự động.</p></section>
    <section className="admin-card"><h2>Google Drive của bạn</h2><p>{settings.connected ? `Đã kết nối: ${settings.driveEmail}` : 'Chưa kết nối Gmail'}</p><label>Google OAuth Client ID<input autoComplete="off" maxLength={250} value={settings.clientId} onChange={e => edit('clientId', e.target.value)} /></label><label>Client secret {settings.hasClientSecret ? '(đã lưu, để trống để giữ nguyên)' : ''}<input type="password" autoComplete="new-password" maxLength={1000} value={secret} onChange={e => setSecret(e.target.value)} /></label><label>Authorized redirect URI — khai báo trong Google Cloud<input readOnly value={settings.callback} onFocus={e => e.target.select()} /></label><p>Lưu Client ID/secret trước, sau đó kết nối đúng Gmail của bạn. Portal tự tạo thư mục riêng, chỉ xin quyền đối với file do ứng dụng tạo.</p><div className="ta-actions"><button type="button" className="button-ghost" disabled={busy || !settings.hasClientSecret || !!secret} onClick={() => void run(async () => { const r = await api<{ url: string }>('connect', {}); location.assign(r.url); })}>Kết nối / cấp lại quyền Google</button><button type="button" className="button-ghost" disabled={busy || !settings.connected} onClick={() => void run(async () => { await api('drive-check', {}); setNotice('Kết nối và quyền ghi thư mục Drive hoạt động.'); })}>Kiểm tra Drive</button></div>{settings.folderId && <p><a href={`https://drive.google.com/drive/folders/${encodeURIComponent(settings.folderId)}`} target="_blank" rel="noreferrer">Mở thư mục riêng trong Drive ↗</a></p>}<label className="ta-check"><input type="checkbox" disabled={!settings.connected} checked={settings.driveEnabled} onChange={e => edit('driveEnabled', e.target.checked)} />Lưu file của lượt mới vào Google Drive</label><p>File đầu vào/kết quả hết hạn sau 30 ngày từ lúc tạo lượt. Cron xóa vĩnh viễn file hết hạn. Không chia sẻ công khai thư mục này.</p></section></div><button className="button-submit" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu cấu hình'}</button></form>}
  </div>;
}
