SET NAMES utf8mb4;

CREATE TABLE PhuHuynh (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  maPhuHuynh VARCHAR(30) NOT NULL,
  nguoiDungId BIGINT UNSIGNED NULL,
  hoTen VARCHAR(255) NOT NULL,
  ngaySinh DATE NULL,
  gioiTinh VARCHAR(20) NULL,
  dienThoai VARCHAR(30) NOT NULL,
  email VARCHAR(255) NULL,
  ngheNghiep VARCHAR(255) NULL,
  diaChi VARCHAR(500) NULL,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_PhuHuynh_donVi_ma (donViId, maPhuHuynh),
  KEY ix_PhuHuynh_dienThoai (dienThoai),
  CONSTRAINT fk_PhuHuynh_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_PhuHuynh_NguoiDung FOREIGN KEY (nguoiDungId) REFERENCES NguoiDung(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HocSinh (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  maHocSinh VARCHAR(30) NOT NULL,
  hoTen VARCHAR(255) NOT NULL,
  tenThuongGoi VARCHAR(100) NULL,
  ngaySinh DATE NOT NULL,
  gioiTinh VARCHAR(20) NULL,
  noiSinh VARCHAR(255) NULL,
  diaChi VARCHAR(500) NULL,
  ngayNhapHoc DATE NULL,
  loaiHinhDaoTao VARCHAR(30) NOT NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'dang_hoc',
  ghiChu TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_HocSinh_donVi_ma (donViId, maHocSinh),
  KEY ix_HocSinh_donVi_trangThai (donViId, trangThai),
  CONSTRAINT fk_HocSinh_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HocSinhPhuHuynh (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  phuHuynhId BIGINT UNSIGNED NOT NULL,
  moiQuanHe VARCHAR(50) NOT NULL COMMENT 'cha, me, ong, ba, nguoi_giam_ho, khac',
  laLienHeChinh TINYINT(1) NOT NULL DEFAULT 0,
  duocDonTre TINYINT(1) NOT NULL DEFAULT 1,
  nhanThongBao TINYINT(1) NOT NULL DEFAULT 1,
  nhanThongTinHocPhi TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_HocSinh_PhuHuynh (hocSinhId, phuHuynhId),
  CONSTRAINT fk_HSPH_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_HSPH_PhuHuynh FOREIGN KEY (phuHuynhId) REFERENCES PhuHuynh(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ChuongTrinhDaoTao (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  maChuongTrinh VARCHAR(30) NOT NULL,
  tenChuongTrinh VARCHAR(255) NOT NULL,
  loaiHinhDaoTao VARCHAR(30) NOT NULL,
  capDo VARCHAR(100) NULL,
  tongSoBuoi INT NULL,
  tongSoGio DECIMAL(10,2) NULL,
  moTa TEXT NULL,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_CTDT_donVi_ma (donViId, maChuongTrinh),
  CONSTRAINT fk_CTDT_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GiaoVien (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  nguoiDungId BIGINT UNSIGNED NULL,
  maGiaoVien VARCHAR(30) NOT NULL,
  hoTen VARCHAR(255) NOT NULL,
  dienThoai VARCHAR(30) NULL,
  email VARCHAR(255) NULL,
  chuyenMon VARCHAR(255) NULL,
  trinhDo VARCHAR(255) NULL,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_GiaoVien_donVi_ma (donViId, maGiaoVien),
  CONSTRAINT fk_GiaoVien_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_GiaoVien_NguoiDung FOREIGN KEY (nguoiDungId) REFERENCES NguoiDung(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LopHoc (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  chuongTrinhDaoTaoId BIGINT UNSIGNED NULL,
  maLop VARCHAR(30) NOT NULL,
  tenLop VARCHAR(255) NOT NULL,
  loaiHinhDaoTao VARCHAR(30) NOT NULL,
  ngayBatDau DATE NULL,
  ngayKetThuc DATE NULL,
  siSoToiDa INT NULL,
  phongHoc VARCHAR(100) NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'chuan_bi',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_LopHoc_donVi_ma (donViId, maLop),
  KEY ix_LopHoc_donVi_trangThai (donViId, trangThai),
  CONSTRAINT fk_LopHoc_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_LopHoc_CTDT FOREIGN KEY (chuongTrinhDaoTaoId) REFERENCES ChuongTrinhDaoTao(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LopHocGiaoVien (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  lopHocId BIGINT UNSIGNED NOT NULL,
  giaoVienId BIGINT UNSIGNED NOT NULL,
  vaiTro VARCHAR(30) NOT NULL DEFAULT 'giao_vien_chinh',
  tuNgay DATE NULL,
  denNgay DATE NULL,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  PRIMARY KEY (id),
  UNIQUE KEY uk_LHGV_lop_gv_tuNgay (lopHocId, giaoVienId, tuNgay),
  CONSTRAINT fk_LHGV_LopHoc FOREIGN KEY (lopHocId) REFERENCES LopHoc(id),
  CONSTRAINT fk_LHGV_GiaoVien FOREIGN KEY (giaoVienId) REFERENCES GiaoVien(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HocSinhLopHoc (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  lopHocId BIGINT UNSIGNED NOT NULL,
  ngayVaoLop DATE NOT NULL,
  ngayRoiLop DATE NULL,
  lyDoRoiLop VARCHAR(500) NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'dang_hoc',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_HSLH_hocSinh_trangThai (hocSinhId, trangThai),
  KEY ix_HSLH_lop_trangThai (lopHocId, trangThai),
  CONSTRAINT fk_HSLH_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_HSLH_LopHoc FOREIGN KEY (lopHocId) REFERENCES LopHoc(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LichHoc (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  lopHocId BIGINT UNSIGNED NOT NULL,
  thuTrongTuan TINYINT NULL COMMENT '1=Thu Hai ... 7=Chu Nhat',
  ngayCuThe DATE NULL,
  gioBatDau TIME NOT NULL,
  gioKetThuc TIME NOT NULL,
  phongHoc VARCHAR(100) NULL,
  lapLaiHangTuan TINYINT(1) NOT NULL DEFAULT 1,
  tuNgay DATE NOT NULL,
  denNgay DATE NULL,
  trangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_LichHoc_lop_tuNgay (lopHocId, tuNgay),
  CONSTRAINT fk_LichHoc_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_LichHoc_LopHoc FOREIGN KEY (lopHocId) REFERENCES LopHoc(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE BuoiHoc (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  lopHocId BIGINT UNSIGNED NOT NULL,
  lichHocId BIGINT UNSIGNED NULL,
  ngayHoc DATE NOT NULL,
  gioBatDau TIME NOT NULL,
  gioKetThuc TIME NOT NULL,
  phongHoc VARCHAR(100) NULL,
  loaiBuoi VARCHAR(30) NOT NULL DEFAULT 'hoc_chinh',
  trangThai VARCHAR(30) NOT NULL DEFAULT 'du_kien',
  lyDoThayDoi VARCHAR(500) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_BuoiHoc_lop_ngay_gio (lopHocId, ngayHoc, gioBatDau),
  CONSTRAINT fk_BuoiHoc_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_BuoiHoc_LopHoc FOREIGN KEY (lopHocId) REFERENCES LopHoc(id),
  CONSTRAINT fk_BuoiHoc_LichHoc FOREIGN KEY (lichHocId) REFERENCES LichHoc(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DiemDanh (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  buoiHocId BIGINT UNSIGNED NOT NULL,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  trangThai VARCHAR(30) NOT NULL COMMENT 'co_mat, vang_co_phep, vang_khong_phep, di_tre, ve_som',
  gioDen TIME NULL,
  gioVe TIME NULL,
  ghiChu VARCHAR(500) NULL,
  nguoiDiemDanhId BIGINT UNSIGNED NULL,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_DiemDanh_buoi_hocSinh (buoiHocId, hocSinhId),
  CONSTRAINT fk_DiemDanh_BuoiHoc FOREIGN KEY (buoiHocId) REFERENCES BuoiHoc(id),
  CONSTRAINT fk_DiemDanh_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_DiemDanh_NguoiDung FOREIGN KEY (nguoiDiemDanhId) REFERENCES NguoiDung(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DonXinPhep (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  donViId BIGINT UNSIGNED NOT NULL,
  hocSinhId BIGINT UNSIGNED NOT NULL,
  phuHuynhId BIGINT UNSIGNED NOT NULL,
  tuNgay DATE NOT NULL,
  denNgay DATE NOT NULL,
  lyDo TEXT NOT NULL,
  trangThai VARCHAR(30) NOT NULL DEFAULT 'cho_tiep_nhan',
  nguoiXuLyId BIGINT UNSIGNED NULL,
  yKienXuLy VARCHAR(500) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_DonXinPhep_DonVi FOREIGN KEY (donViId) REFERENCES DonVi(id),
  CONSTRAINT fk_DonXinPhep_HocSinh FOREIGN KEY (hocSinhId) REFERENCES HocSinh(id),
  CONSTRAINT fk_DonXinPhep_PhuHuynh FOREIGN KEY (phuHuynhId) REFERENCES PhuHuynh(id),
  CONSTRAINT fk_DonXinPhep_NguoiXuLy FOREIGN KEY (nguoiXuLyId) REFERENCES NguoiDung(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
